// React/src/App.tsx
import React, { useRef, useCallback, useMemo } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import TreeList, { Column, Toolbar, Item } from 'devextreme-react/tree-list';
import { Workbook } from 'exceljs';
import saveAs from 'file-saver';
import { exportTreeList } from './excelExporter';
import { employees } from './data';

const expandedRowKeys = [1];

function App(): JSX.Element {
  const treeList = useRef<TreeList>(null);

  const exportToExcel = useCallback(() => {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Employees');

    exportTreeList({
      component: treeList.current?.instance,
      worksheet,
    })
      .then(() => {
        workbook.xlsx
          .writeBuffer()
          .then((buffer) => {
            saveAs(
              new Blob([buffer], { type: 'application/octet-stream' }),
              'Employees.xlsx',
            );
          })
          .catch(() => {});
      })
      .catch(() => {});
  }, []);

  const exportButtonOptions = useMemo(
    () => ({
      icon: 'xlsxfile',
      onClick: exportToExcel,
    }),
    [],
  );

  return (
    <TreeList
      ref={treeList}
      id='employees'
      dataSource={employees}
      rootValue={-1}
      keyExpr='ID'
      parentIdExpr='Head_ID'
      defaultExpandedRowKeys={expandedRowKeys}
      showRowLines={true}
      showBorders={true}
      columnAutoWidth={true}
    >
      <Column dataField='Title' caption='Position' />
      <Column dataField='Full_Name' />
      <Column dataField='City' />
      <Column dataField='State' />
      <Column dataField='Mobile_Phone' />
      <Column dataField='Hire_Date' dataType='date' />

      <Toolbar>
        <Item
          name='exportToXlsx'
          widget='dxButton'
          locateInMenu='auto'
          options={exportButtonOptions}
        />
      </Toolbar>
    </TreeList>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { DxTreeListComponent } from 'devextreme-angular';
import { Employee, Service } from './app.service';
import { Workbook } from 'exceljs';
import { saveAs } from 'file-saver';

import { exportTreeList } from './excelExporter';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  @ViewChild('treeList', { static: false }) treeList!: DxTreeListComponent;

  employees: Employee[];

  expandedRowKeys: number[];

  exportButtonOptions: any;

  constructor(service: Service) {
    this.employees = service.getEmployees();
    this.expandedRowKeys = [1];
    this.exportButtonOptions = {
      icon: 'xlsxfile',
      onClick: this.exportToExcel.bind(this),
    };
  }

  exportToExcel(): void {
    const workbook = new Workbook();
    const worksheet = workbook.addWorksheet('Employees');

    exportTreeList({
      component: this.treeList.instance,
      worksheet,
    })
      .then(() => {
        workbook.xlsx
          .writeBuffer()
          .then((buffer) => {
            saveAs(new Blob([buffer], { type: 'application/octet-stream' }), 'Employees.xlsx');
          })
          .catch(() => {});
      })
      .catch(() => {});
  }
}

<dx-tree-list
  #treeList
  id="tree-list"
  [dataSource]="employees"
  [rootValue]="-1"
  keyExpr="ID"
  parentIdExpr="Head_ID"
  [(expandedRowKeys)]="expandedRowKeys"
  [showRowLines]="true"
  [showBorders]="true"
  [columnAutoWidth]="true"
>
  <dxi-column dataField="Title" caption="Position" />
  <dxi-column dataField="Full_Name" />
  <dxi-column dataField="City" />
  <dxi-column dataField="State" />
  <dxi-column dataField="Mobile_Phone" />
  <dxi-column dataField="Hire_Date" dataType="date" />

  <dxo-toolbar>
    <dxi-item
      name="exportToXlsx"
      widget="dxButton"
      locateInMenu="auto"
      [options]="exportButtonOptions"
    />
  </dxo-toolbar>
</dx-tree-list>
